#!/bin/sh /etc/rc.common
# MiWRT app service: status collector plus the network announcement the app looks for.
START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/miwrt-hubd
	procd_set_param respawn 3600 5 0
	procd_add_mdns "miwrt" "tcp" "443" "v=1" "path=/cgi-bin/miwrt" "tls=1"
	procd_close_instance

	# smart-home discovery relay, only where a separate IoT network exists
	if [ -d /sys/class/net/br-iot ] && [ -d /sys/class/net/br-lan ]; then
		procd_open_instance relay
		procd_set_param command /usr/sbin/miwrt-discovery-relay br-iot br-lan
		procd_set_param respawn 3600 10 0
		procd_close_instance
	fi
}
