#!/bin/sh /etc/rc.common
# MiWRT app service: status collector plus the network announcement the app looks for.
START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/miwrt-hubd
	procd_set_param respawn 3600 5 0
	procd_add_mdns "miwrt" "tcp" "443" "v=1" "path=/cgi-bin/miwrt" "tls=1"
	procd_close_instance
}
