#!/bin/sh
# MiWRT: the stock default hostname OpenWrt becomes MiWRT (LuCI page
# titles, the shell prompt, DHCP). A hostname the user set stays as it is.

[ "$(uci -q get system.@system[0].hostname)" = "OpenWrt" ] || exit 0

uci set system.@system[0].hostname='MiWRT'
uci commit system
echo MiWRT > /proc/sys/kernel/hostname

exit 0
